name: Update Packages
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

permissions:
    contents: write

jobs:
    run-update:
        runs-on: ubuntu-latest
        outputs:
            needs-commit: ${{steps.run-updater.outputs.commit}}
        steps:
            - uses: actions/checkout@v5
            - uses: actions/cache@v4
              name: Cache cargo
              id: cache-cargo
              with:
                path: |
                    target
                    ~/.cargo
                key: ${{runner.os}}-cargo-${{hashFiles('Cargo.*')}}-${{hashFiles('.github/workflows/update-packages.yml')}}
            - uses: cachix/install-nix-action@v31
            - uses: cachix/cachix-action@v16
              with:
                  name: devenv
            - name: Install devenv.sh
              run: nix profile add nixpkgs#devenv
            - name: Run updater
              id: run-updater
              run: echo "commit=$(devenv shell -- cargo run)" >> $GITHUB_OUTPUT
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - name: Commit result
              id: commit-result
              if: ${{steps.run-updater.outputs.commit == 'true'}}
              uses: stefanzweifel/git-auto-commit-action@v7
              with:
                commit_message: "AUTO[R${{github.run_number}} - ${{github.run_id}}] Update Packages"
                branch: main
                


